### ISSUE TITLE
New rule: Test on-site links to sections to see if they exist

### ISSUE THREAD

**Issue by Elchi3** [mdn/doc-linter-rules#18]
Original issue https://github.com/Elchi3/mdn-doc-tests/issues/145.

Check anchor links on the current page and throw an error if those sections do not exist.

Link to #nope should throw:

```
<h2 id="yay">yay</h2>
<a href="#yay">Link to yay</a>

<a href="#nope">Link to nope</a>
```

**Comment by MatonAnthony** [comment]
Are anchors allowed everywhere or only in titles ?

**Comment by SebastianZ** [comment]
While they most often refer to headlines, anchors are allowed everywhere. So you should loop over the `id`s of all elements in the article. I.e. first you need to get all anchor links via something like `document.querySelectorAll("a[href^='#']")` and then check for each one whether it refers to an element with the ID., so something like `document.querySelectorAll("[id]")` to get all of them.

Sebastian

**Comment by MatonAnthony** [comment]
Ok, thank you.
